// <auto-generated />
namespace ProjectUni.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createmenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createmenu));
        
        string IMigrationMetadata.Id
        {
            get { return "202002211442492_create menu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
